### ISSUE TITLE
Package not inside packagist.org

### ISSUE THREAD

**Issue by GhaziTriki** [xfra35/f3-access#1]
Hello,

Great job. Can you please add this package to http://packagist.org as I couldn't find it?

**Comment by xfra35** [comment]
Hi, thanks for warning.
Should be ok now.

**Comment by GhaziTriki** [comment]
Hello,

Good, I still can't find it. Can you point us to the page please? I guess `composer require xfra35/f3-access` should work but it doesn't.

**Comment by xfra35** [comment]
Hey @GhaziTriki, that's because I have not used semantic versioning. If you look at the [package page](https://packagist.org/packages/xfra35/f3-access), there's only one version available, called `dev-master`.

So you should call `composer require xfra35/f3-access:dev-master`.

But wait a bit, I'll specify a meaningful version for the plugin.

**Comment by xfra35** [comment]
Now it has `v1.0.0` version and you can use `composer require xfra35/f3-access`.

**Comment by GhaziTriki** [comment]
Can you also update the dev-master version to use the dev-master version of fatfree-core?

**Comment by xfra35** [comment]
Can we do that? I don't think we can have conditional `require` directives in composer.json.

**Comment by GhaziTriki** [comment]
I don't think we can have conditional directives, however the issue is when using dev-master version of fatfree-core and dev-master version of f3-access a collision will happen because the f3-access dev-master version uses a tagged version of fatfree-core. I would be nice to make it match dev-master for development purpose.

**Comment by xfra35** [comment]
Hmm I thought it would be possible using the `require-dev` directive but after reading https://github.com/composer/composer/issues/3742, the conclusion is no. You can't define two different versions of a package for prod and dev environments.

So here's how to do it instead: define 2 composer.json files. One for production and one for development:

**composer.prod.json**

``` json
{
    "require": {
        "xfra35/f3-access": "1.*"
    }
}
```

**composer.dev.json**

``` json
{
    "require": {
        "bcosca/fatfree-core": "dev-master as 3.x.x-dev",
        "xfra35/f3-access": "dev-master"
    }
}
```

Then switch one or the other depending on your environment:

**production**

``` bash
export COMPOSER=composer.prod.json; composer install
```

**development**

``` bash
export COMPOSER=composer.dev.json; composer install
```

**Comment by GhaziTriki** [comment]
It does not work because the published version of f3-access is forced to "3.5" version of fatfree-core. Is it possible to require-dev the "dev-master" of fatfree-core in your composer;json?

**Comment by xfra35** [comment]
No `require-dev` doesn't help here because it's supposed to require _extra_ packages, not the same package with a different version.

Why do you say that it doesn't work? I've tried it and it's working well. The trick is to use an [alias](https://getcomposer.org/doc/articles/aliases.md) to replace `3.x.x` by `dev-master`. Hence the line `"bcosca/fatfree-core": "dev-master as 3.x.x-dev"`.

**Comment by rnolan** [comment]
Trying to use this on AWS - Elastic Beanstalk, on deployment, none of the folders in f3-access exist on the server. I *think* it may be due to the inclusion of the .git folder in composer which may be breaking EB deployment.
