### ISSUE TITLE
 PHP Warning: Illegal offset type in access.php line 29

### ISSUE THREAD

**Issue by Houssine-BA** [xfra35/f3-access#2]
Hi there,

When adding an access rule to an ajax method for multiple role types like below

`allow DELETE @course_delete [ajax] = admin,moderator,presenter`

We get the following error

`PHP Warning: Illegal offset type in access.php line:29`

https://github.com/xfra35/f3-access/blob/master/lib/access.php#L29

**Comment by xfra35** [comment]
Hi @hossine, this syntax is not valid. The plugin is not meant to provide a different access level for ajax and non-ajax requests.

**Comment by Houssine-BA** [comment]
Thank you for your reply. Could the plugin be updated to add that level of detail for ajax and non ajax requests? It would be very helpful to have it.

**Comment by xfra35** [comment]
I'm not convinced that it's a good idea. It looks to me that if you need to give different access level to ajax and non-ajax requests, you should review your architecture.

But I may be missing something obvious. Can you give me a use case?

**Comment by GhaziTriki** [comment]
Hi @xfra35,

In the use case we have it is not possible to delete a record from the database without confirming the deletion on clicking "Yes" on a dialog box. Once "Yes" is clicked we make an ajax call to delete the record. Deleting the records without ajax in our case is risky.

**Comment by xfra35** [comment]
So you must be having something like:

``` ini
[routes]
GET @course_get : /course/@id = Course->show
DELETE @course_delete : /course/@id [ajax] = Course->delete

[ACCESS.rules]
deny DELETE @course_delete = *
allow DELETE @course_delete = admin,moderator,presenter
```

right?

Then I have two remarks:
1. The framework aliases are aliases for _URI_ not verbs, so `@course_get` and `@course_delete` map to the same data, namely `/course/@id`. In other words, you just need one alias `@course`.
2. Your access rules specify that advanced users (admin, moderator, presenter) can delete a course. We don't care if it's ajax or not here because, if it's not ajax, the framework will respond with a 404 before the plugin is even triggered.

Here's the flow:
- **Case 1: HTTP request to an existing resource** => F3 calls the controller, which in turn ask the access plugin to check if the current user is authorized.
- **Case 2: HTTP request to a non-existing resource** => F3 triggers a 404. The controller is not called (therefore the access plugin neither).

You're referring to case 2, so there's nothing the access plugin can do about it, since this case is handled by the framework (F3 won't allow deleting records without ajax).

**Comment by GhaziTriki** [comment]
I completely missed the fact that the framework will tirrger a 404. The access by verb should be enough then. Thanks !!!
